services:
  mrwilde-website:
    build: .
    ports:
      - "8182:80"
    restart: unless-stopped
    container_name: mrwilde-site

  # Optional: Add a reverse proxy with SSL
  nginx-proxy:
   image: nginx:alpine
   ports:
     - "8443:443"
   volumes:
     - ./nginx.conf:/etc/nginx/nginx.conf:ro
     - ./ssl:/etc/ssl/certs:ro
   depends_on:
     - mrwilde-website
   restart: unless-stopped